version: '3'
services:

  zookeeper:
    container_name: poc-zookeeper
    image: confluentinc/cp-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: poc-kafka
    image: confluentinc/cp-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      
  redis:
    image: redis
    container_name: poc-redis
    restart: always
    ports:
      - 6379:6379
